### ISSUE TITLE
Something wrong with ConverterToSSF

### ISSUE THREAD

**Issue by vadyushkins** [viabzalov/YAFOLPS#1]
## I think there is a problem somewhere in the ConverterToSSF.hs
* ``stack build && stack exec -- YAFOLPS-exe --i test/exampleTop.txt -s`` Prints: 
```Converted SSF:
SSF 
    { quants = []
    , matrix = []
    } 
```
* ``stack build && stack exec -- YAFOLPS-exe --i test/exampleBottom.txt -s`` Prints: 
```Converted SSF:
SSF 
    { quants = []
    , matrix = []
    } 
```
* ``stack build && stack exec -- YAFOLPS-exe --i test/example4.txt -s`` Prints: 
```Converted SSF:
SSF 
    { quants = []
    , matrix = []
    } 
```

**Comment by SergeyKuz1001** [comment]
[Fixed](https://github.com/viabzalov/YAFOLPS/commit/6abdd1724d34a90b18178d22d7241318cdce7217)
